# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-DBI-Plugin-Param
version:      0.03
version_from: lib/Class/DBI/Plugin/Param.pm
installdirs:  site
requires:
    Class::DBI:                    3.0.11
    Test::More:                    0.32

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
